"""OCI Resource Manager Module.

Provides functions to manage Resource Manager Stacks and Jobs
for automated Terraform deployment.
"""

import base64
import json
import logging
import os
import shutil
import tempfile
import time
import zipfile
from pathlib import Path

logger = logging.getLogger(__name__)

from src.oci_cli import run_command


def zip_terraform_dir(terraform_dir: str) -> str:
    """Zip a Terraform directory for Resource Manager upload.

    Args:
        terraform_dir: Path to directory containing .tf files.

    Returns:
        Path to the created zip file.

    Raises:
        FileNotFoundError: If terraform_dir does not exist.
        ValueError: If no .tf files found.
    """
    tf_path = Path(terraform_dir)
    if not tf_path.is_dir():
        raise FileNotFoundError(f"Terraform directory not found: {terraform_dir}")

    tf_files = list(tf_path.glob("*.tf")) + list(tf_path.glob("*.tfvars"))
    sh_files = list(tf_path.glob("*.sh"))
    all_files = tf_files + sh_files

    if not tf_files:
        raise ValueError(f"No .tf files found in {terraform_dir}")

    zip_path = str(tf_path.parent / "terraform.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in all_files:
            zf.write(f, f.name)  # Flat structure (no subdirs)

    return zip_path


def create_stack(
    compartment_id: str,
    terraform_dir: str,
    display_name: str,
    terraform_version: str = "1.5.x",
) -> str:
    """Create a Resource Manager Stack from a Terraform directory.

    Zips the directory and uploads it. If a stack with the same name
    already exists, updates it instead.

    Args:
        compartment_id: Compartment OCID.
        terraform_dir: Path to Terraform directory.
        display_name: Stack display name.
        terraform_version: Terraform version constraint.

    Returns:
        Stack OCID.
    """
    zip_path = zip_terraform_dir(terraform_dir)

    # Check for existing stack with same name
    existing = _find_stack_by_name(compartment_id, display_name)
    if existing:
        _update_stack(existing, zip_path)
        return existing

    result = run_command([
        "resource-manager", "stack", "create",
        "--compartment-id", compartment_id,
        "--config-source", zip_path,
        "--display-name", display_name,
        "--description", "Auto-generated by OCI Demo Builder",
        "--terraform-version", terraform_version,
    ])
    return result["data"]["id"]


def _find_stack_by_name(compartment_id: str, display_name: str) -> str | None:
    """Find an existing stack by display name.

    Returns:
        Stack OCID if found, None otherwise.
    """
    try:
        result = run_command([
            "resource-manager", "stack", "list",
            "--compartment-id", compartment_id,
            "--display-name", display_name,
        ])
        stacks = result.get("data", [])
        for stack in stacks:
            if stack.get("lifecycle-state") == "ACTIVE":
                return stack["id"]
    except Exception:
        pass
    return None


def _update_stack(stack_id: str, zip_path: str) -> None:
    """Update an existing stack with new Terraform config."""
    run_command([
        "resource-manager", "stack", "update",
        "--stack-id", stack_id,
        "--config-source", zip_path,
        "--force",
    ])


def run_plan(stack_id: str) -> str:
    """Run a Plan job on a stack.

    Args:
        stack_id: Stack OCID.

    Returns:
        Job OCID.
    """
    result = run_command([
        "resource-manager", "job", "create",
        "--stack-id", stack_id,
        "--operation", "PLAN",
    ])
    return result["data"]["id"]


def run_apply(stack_id: str) -> str:
    """Run an Apply job on a stack.

    Args:
        stack_id: Stack OCID.

    Returns:
        Job OCID.
    """
    result = run_command([
        "resource-manager", "job", "create",
        "--stack-id", stack_id,
        "--operation", "APPLY",
        "--apply-job-plan-resolution", "AUTO_APPROVED",
    ])
    return result["data"]["id"]


def run_destroy(stack_id: str) -> str:
    """Run a Destroy job on a stack.

    Args:
        stack_id: Stack OCID.

    Returns:
        Job OCID.
    """
    result = run_command([
        "resource-manager", "job", "create",
        "--stack-id", stack_id,
        "--operation", "DESTROY",
        "--apply-job-plan-resolution", "AUTO_APPROVED",
    ])
    return result["data"]["id"]


def get_job_status(job_id: str) -> dict:
    """Get the status of a job.

    Args:
        job_id: Job OCID.

    Returns:
        Dict with job details including lifecycle_state.
    """
    result = run_command([
        "resource-manager", "job", "get",
        "--job-id", job_id,
    ])
    data = result["data"]
    return {
        "id": data["id"],
        "operation": data["operation"],
        "lifecycle_state": data["lifecycle-state"],
        "time_created": data.get("time-created"),
        "time_finished": data.get("time-finished"),
    }


def wait_for_job(
    job_id: str,
    timeout: int = 3600,
    interval: int = 30,
) -> dict:
    """Poll a job until completion or timeout.

    Args:
        job_id: Job OCID.
        timeout: Maximum wait time in seconds (default 3600 = 60 min).
        interval: Polling interval in seconds (default 30).

    Returns:
        Final job status dict.

    Raises:
        TimeoutError: If job does not complete within timeout.
    """
    start = time.time()
    while True:
        status = get_job_status(job_id)
        state = status["lifecycle_state"]

        if state in ("SUCCEEDED", "FAILED", "CANCELED"):
            return status

        elapsed = time.time() - start
        if elapsed >= timeout:
            raise TimeoutError(
                f"Job {job_id} timed out after {timeout}s. "
                f"Current state: {state}"
            )

        time.sleep(interval)


def get_job_logs(job_id: str) -> str:
    """Get logs for a job.

    Args:
        job_id: Job OCID.

    Returns:
        Log content as string.
    """
    result = run_command([
        "resource-manager", "job",
        "get-job-detailed-log-content",
        "--job-id", job_id,
    ])
    return result.get("data", "")


def get_stack_outputs(stack_id: str, job_id: str) -> dict:
    """Get Terraform outputs from a completed Apply job.

    Attempts to retrieve outputs using the following strategies:
    1. Primary: Get terraform.tfstate via get-job-tf-state and extract outputs
    2. Fallback: Parse outputs from job logs

    Args:
        stack_id: Stack OCID.
        job_id: Apply Job OCID.

    Returns:
        Dict of Terraform output values.
    """
    # Strategy 1: Get outputs from terraform.tfstate
    try:
        result = run_command([
            "resource-manager", "job", "get-job-tf-state",
            "--job-id", job_id,
        ])
        # The response may be base64-encoded or raw JSON
        tf_state_data = result.get("data", result)
        if isinstance(tf_state_data, str):
            try:
                tf_state_data = json.loads(base64.b64decode(tf_state_data))
            except Exception:
                tf_state_data = json.loads(tf_state_data)
        outputs = {}
        raw_outputs = tf_state_data.get("outputs", {})
        for key, val in raw_outputs.items():
            outputs[key] = val.get("value", val)
        if outputs:
            return outputs
    except Exception:
        logger.debug("Failed to get outputs from tf-state, falling back to log parsing")

    # Strategy 2 (Fallback): Parse outputs from job logs
    try:
        output_result = run_command([
            "resource-manager", "job", "get-job-logs",
            "--job-id", job_id,
        ])
        outputs = _parse_outputs_from_logs(output_result)
        if outputs:
            return outputs
    except Exception:
        logger.debug("Failed to get outputs from job logs")

    logger.warning(
        "Could not retrieve stack outputs for job %s. "
        "Both tf-state and log parsing methods returned empty results.",
        job_id,
    )
    return {}


def _parse_outputs_from_logs(log_data: dict) -> dict:
    """Parse Terraform outputs from job log data.

    Returns:
        Dict of output key-value pairs.
    """
    outputs = {}
    items = log_data.get("data", [])
    capture = False
    for item in items:
        message = item.get("message", "")
        if "Outputs:" in message:
            capture = True
            continue
        if capture and "=" in message:
            parts = message.split("=", 1)
            key = parts[0].strip()
            value = parts[1].strip().strip('"')
            outputs[key] = value
    return outputs


def save_stack_outputs(
    outputs: dict,
    stack_id: str,
    job_id: str,
    project_name: str,
    output_path: str,
) -> str:
    """Save stack outputs to JSON file with metadata.

    Args:
        outputs: Terraform output values.
        stack_id: Stack OCID.
        job_id: Apply Job OCID.
        project_name: Project name.
        output_path: Path to write JSON file.

    Returns:
        Path to the output file.
    """
    data = {
        **outputs,
        "_stack_id": stack_id,
        "_apply_job_id": job_id,
        "_project_name": project_name,
    }
    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)
    return output_path
